import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="retro" lang="en">
      <body className="max-w-[2000px] max-h-full mx-auto">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
